export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS'
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const ADD_LOADED_PRODUCTS = 'ADD_LOADED_PRODUCTS'

export const ORDER_HISTORY_RESET = 'ORDER_HISTORY_RESET'

export const UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN'
export const LOCATION_UPDATE = 'LOCATION_UPDATE'
export const UPDATE_MAIN_SCREEN = 'UPDATE_MAIN_SCREEN'